/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "MainTask.h"
#include "wm_download.h"
#include "wm_bluetooth.h"
#include "wm_scan.h"
#include "wm_mabot.h"
#include "wm_downfail.h"
#include "wm_scanagain.h"
#include "wm_disconnect.h"

#include "usart.h"
#include "oled.h"
#include "ble_function.h"
#include "message_manager.h"

static __INLINE BaseType_t recive_gui_msg(GUI_MSG *gui_msg,TickType_t xTicksToWait)
{
    return xQueueReceive(gui_msg_queue,gui_msg,xTicksToWait);
}

static void create_mabot()
{
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    WM_DeleteWindow(hwin_disconnect);
    WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain);
    create_mabot_window();
    hwin_download = WM_HWIN_NULL;
    printf("create mabot window\r\n");
}
static void create_download()
{
    if(hwin_download == WM_HWIN_NULL)
    {
        WM_DeleteWindow(hwin_mabot);
        WM_DeleteWindow(hwin_bluetooth);
        WM_DeleteWindow(hwin_download);
        WM_DeleteWindow(hwin_disconnect);
        WM_DeleteWindow(hwin_downfail);
        WM_DeleteWindow(hwin_bluetooth);
        WM_DeleteWindow(hwin_scan);
        WM_DeleteWindow(hwin_scanagain); 
        create_download_window();
    }
    printf("create download window\r\n");
}
static void create_downfail()
{
    WM_DeleteWindow(hwin_mabot);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    WM_DeleteWindow(hwin_disconnect);
    //WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain); 
    create_downfail_window();
    hwin_download = WM_HWIN_NULL;
    printf("create downfail window\r\n");
}
static void create_scan()
{
    WM_DeleteWindow(hwin_mabot);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    WM_DeleteWindow(hwin_disconnect);
    WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    //WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain);  
    create_scan_window();
    hwin_download = WM_HWIN_NULL;
    printf("create scan window\r\n");
}
static void create_scanagain()
{
    WM_DeleteWindow(hwin_mabot);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    WM_DeleteWindow(hwin_disconnect);
    //WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain); 
    create_scanagain_window();
    hwin_download = WM_HWIN_NULL;
    printf("create scanagain window\r\n");
}
static void create_bluetooth()
{
    WM_DeleteWindow(hwin_mabot);
    //WM_HideWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    WM_DeleteWindow(hwin_disconnect);
    WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain); 
    create_bluetooth_window();
    hwin_download = WM_HWIN_NULL;
    printf("create bluetooth window\r\n");
}
static void create_disconnect()
{
    WM_DeleteWindow(hwin_mabot);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_download);
    //WM_DeleteWindow(hwin_disconnect);
    WM_DeleteWindow(hwin_downfail);
    WM_DeleteWindow(hwin_bluetooth);
    WM_DeleteWindow(hwin_scan);
    WM_DeleteWindow(hwin_scanagain); 
    create_disconnect_window();
    hwin_download = WM_HWIN_NULL;
    printf("create disconnect window\r\n");
}

void msg_poll(void)
{
    if ( recive_gui_msg(&gui_msg,pdMS_TO_TICKS(5)) == pdPASS )
    {
        switch(gui_msg.type)
        {
            case idel:                
                create_mabot();
            break;
            case download:
                //bug
                create_download();
                break;
            case download_failure:
                create_downfail();
                break;
            case ble_serching: 
                create_scan();
                break;
            case ble_serch_failure: 
                create_scanagain();
                break; 
            case ble_list_head:
                create_bluetooth();
                break;
            case ble_next: GUI_StoreKeyMsg(GUI_KEY_DOWN, 1);break;
            case ble_confirm:GUI_StoreKeyMsg(GUI_KEY_ENTER, 1); break;
            case ble_connect_failure: 
                create_disconnect();
                break;
            case bat_power:break;
        }
    }
}

void MainTask(void)
{
    /* emwin init */
    GUI_Init();  
    oled_set_normal();

    create_mabot_window();

    while(1)
    {
        GUI_Delay(10);

        oled_end_draw();      
        oled_start_draw();

        msg_poll();

        taskYIELD();
    }
}

/*************************** End of file ****************************/
