/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "wm_bluetooth.h"

#include <stdlib.h>

#include "usart.h"
#include "llist.h"
#include "ble_function.h"
#include "system.h"
#include "message_manager.h"

#define ID_FRAMEWIN_0             (GUI_ID_USER + 0x00)

#define ID_TIMER_UPDATE_TITLE     0

typedef struct ble_msg_index_struct
{
    struct list_node node;
    uint8_t search_index;
    uint8_t listbox_index;
}BLE_MSG_INDEX;

WM_HWIN hwin_bluetooth = WM_HWIN_NULL;
static WM_HTIMER htimer_update_title = WM_HWIN_NULL;       //static image

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = 
{
    { FRAMEWIN_CreateIndirect,  "Framewin",  ID_FRAMEWIN_0,  0, 0,  128, 64, 0, 0x64, 0 },
    { LISTBOX_CreateIndirect,   "Listbox",   GUI_ID_LISTBOX0,   0, 0,  118, 45, 0, 0x0,  0 },
}; 

LIST_HEAD(index_list);
static void index_list_free()
{
    struct ble_msg_index_struct *ble_msg_index=NULL;
    struct list_node *entry = NULL;
    if (index_list.first == NULL)return;
    for ( entry = index_list.first; entry != NULL; )
    {
        ble_msg_index = list_entry(entry, struct ble_msg_index_struct, node);
        entry = entry->next;
        free(ble_msg_index);
    }
    INIT_LIST_HEAD(&index_list);
}

static void wm_bluetooth_init(const WM_MESSAGE * pMsg)
{
    WM_HWIN hitem = WM_HWIN_NULL;

    htimer_update_title = WM_CreateTimer(WM_GetClientWindow(pMsg->hWin), ID_TIMER_UPDATE_TITLE, 2000, 0);
    
    hitem = pMsg->hWin;
    FRAMEWIN_SetText(hitem, "Bluetooth");
    FRAMEWIN_SetFont(hitem, GUI_FONT_10_ASCII);

    hitem = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTBOX0);
    WM_SetFocus(hitem);
    LISTBOX_SetFont(hitem,GUI_FONT_16B_ASCII);
    LISTBOX_SetAutoScrollH(hitem,1);
    LISTBOX_SetAutoScrollV(hitem,1);
    LISTBOX_EnableWrapMode(hitem,1);
}

static void wm_bluetooth_update(const WM_MESSAGE * pMsg)
{
    int     item = 0;
    int     items = 0;
    int     index = 0;
    WM_HWIN hitem = WM_HWIN_NULL;
    struct  ble_struct *ble_msg = NULL;
    struct  ble_msg_index_struct *ble_msg_index = NULL;
    struct  list_head *head = NULL;
    struct  list_node *entry = NULL; 
    if(gui_msg.type == ble_list_head)
    {
        if((struct list_head *)gui_msg.data.ble_list_head != NULL)
        {
            //DeleteItems
            hitem = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTBOX0);
            items = LISTBOX_GetNumItems(hitem);
            for(item = LISTBOX_GetNumItems(hitem)-1;item >= 0;item--)
            {
                LISTBOX_DeleteItem(hitem,item);
            }
            index_list_free();
            index = 0;
            if (((struct list_head *)gui_msg.data.ble_list_head)->first == NULL)return;
            for ( entry = ((struct list_head *)gui_msg.data.ble_list_head)->first; entry != NULL; entry = entry->next )
            {
                ble_msg = list_entry(entry, struct ble_struct, node);
                LISTBOX_AddString(hitem,ble_msg->name);
                ble_msg_index = (struct ble_msg_index_struct *)malloc(sizeof(struct ble_msg_index_struct));
                if(ble_msg_index == NULL)ERROR("\r\n");;
                ble_msg_index->search_index = ble_msg->index;
                ble_msg_index->listbox_index = (char)index;
                index++;
                ble_msg_index->node.next = NULL;
                list_add(&ble_msg_index->node,&index_list);   
            } 
            LISTBOX_SetSel(hitem,0);
            gui_msg.data.ble_list_head = NULL;
        }
    }
}

static void wm_bluetooth_send_msg(const WM_MESSAGE * pMsg)
{
    int     item = 0;
    struct  list_node *entry = NULL; 
    struct  ble_msg_index_struct *ble_msg_index = NULL;
    if(index_list.first != NULL)
    {
        item = LISTBOX_GetSel(WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTBOX0));
        for ( entry = index_list.first; entry != NULL; )
        {
            ble_msg_index = list_entry(entry, struct ble_msg_index_struct, node);
            if(item == (int)ble_msg_index->listbox_index)
            {  
                if(xQueueSend(ble_index_queue,(char*)&ble_msg_index->search_index,pdMS_TO_TICKS(300)) != pdPASS)
                {
                    ERROR("\r\n");
                }
                break;
            } 
            entry = entry->next;
        }
    }
}

static void wm_bluetooth_update_title(const WM_MESSAGE * pMsg)
{
    char    title_buf[20];
    WM_HWIN hitem = WM_HWIN_NULL;
    hitem = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTBOX0);
    if(LISTBOX_GetNumItems(hitem) != 0)
    {
        sprintf(title_buf, "Bluetooth %d/%d",LISTBOX_GetSel(hitem)+1,LISTBOX_GetNumItems(hitem));   
    }else
    {
        sprintf(title_buf, "Bluetooth %d/%d",LISTBOX_GetSel(hitem),LISTBOX_GetNumItems(hitem));
    }
    FRAMEWIN_SetText(pMsg->hWin, title_buf);
}

static void wm_bluetooth_free_window_object(const WM_MESSAGE * pMsg)
{
    // emwin-V5.04 WM_DeleteWindow() now also deletes any associated timer but
    WM_DeleteTimer(htimer_update_title);
    htimer_update_title = WM_HWIN_NULL;
    WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTBOX0));
    WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0));
    index_list_free();
}


static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hitem = WM_HWIN_NULL;
    int     ncode = 0;
    int     id = 0;
    switch (pMsg->MsgId)
    {
        case WM_INIT_DIALOG:
            wm_bluetooth_init(pMsg);
            break;
        case WM_POST_PAINT:
            wm_bluetooth_update(pMsg);
            break;
        case WM_DELETE:
            wm_bluetooth_free_window_object(pMsg);
            break;
        case WM_NOTIFY_PARENT:
            id    = WM_GetId(pMsg->hWinSrc);
            ncode = pMsg->Data.v;
            switch(id)
            {
                case GUI_ID_LISTBOX0: 
                    switch(ncode)
                    {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            break;
                    }
                    break;
            }
            break;
        case WM_KEY:
            id = ((WM_KEY_INFO*)(pMsg->Data.p))->Key;
            switch(id)
            {
                case GUI_KEY_ENTER:             
                    wm_bluetooth_send_msg(pMsg);
                    break;
            }
            break;
        case WM_TIMER:
            id = WM_GetTimerId(pMsg->Data.v);
            switch (id)
            {
                case ID_TIMER_UPDATE_TITLE:
                    wm_bluetooth_update_title(pMsg);
                    WM_RestartTimer(pMsg->Data.v, 2000);
                    break;
            }
            break;
        default:
            WM_DefaultProc(pMsg);
        break;
    }
}

void create_bluetooth_window(void) 
{
    hwin_bluetooth = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
}

/*************************** End of file ****************************/
