/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "wm_scanagain.h"
#include "bmp_scan_again.h"

#include "usart.h"
#include "message_manager.h"

#define ID_WINDOW_SCAN       (GUI_ID_USER + 0x00)
#define ID_IMAGE_SCANAGAIN   (GUI_ID_USER + 0x01)

WM_HWIN hwin_scanagain = WM_HWIN_NULL;

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = 
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_SCAN, 0, 0, 128, 64, 0, 0x0, 0 },
    { IMAGE_CreateIndirect,  "Image" , ID_IMAGE_SCANAGAIN,  0, 0, 128, 64, 0, 0x0, 0 },
};

static void wm_scanagain_free_window_object(const WM_MESSAGE * pMsg)
{
    WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, ID_IMAGE_SCANAGAIN));
    WM_DeleteWindow(WM_GetDialogItem(pMsg->hWin, ID_WINDOW_SCAN));
}

static void _cbDialog(WM_MESSAGE * pMsg) 
{
    switch (pMsg->MsgId) 
    {
        case WM_INIT_DIALOG:
            IMAGE_SetBitmap(WM_GetDialogItem(pMsg->hWin, ID_IMAGE_SCANAGAIN),&bmscan_again_128x64);
            break;
        case WM_DELETE:
            wm_scanagain_free_window_object(pMsg);
            break;  
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

void create_scanagain_window(void)
{
    hwin_scanagain = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

/*************************** End of file ****************************/
