/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file:                                       *
* Dimensions:  23 * 14                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#ifndef __BMP_SCAN_H
#define __BMP_SCAN_H

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
    #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmscan1_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan2_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan3_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan4_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan5_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan6_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan7_128x64;
extern GUI_CONST_STORAGE GUI_BITMAP bmscan8_128x64;

#endif
/*************************** End of file ****************************/
