/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: battery0_23x14                                        *
* Dimensions:  23 * 14                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#ifndef __BMP_BATTERY_H
#define __BMP_BATTERY_H

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
    #define GUI_CONST_STORAGE const
#endif

#define BATTERY_FALSE_FULL_POWER      100
#define BATTERY_FALSE_MEDIUM_POWER    67
#define BATTERY_FALSE_LOW_POWER       34
#define BATTERY_FALSE_ZERO_POWER      0

extern GUI_CONST_STORAGE GUI_BITMAP bmbattery0_23x14;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery34_23x14;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery67_23x14;
extern GUI_CONST_STORAGE GUI_BITMAP bmbattery100_23x14;

#endif
/*************************** End of file ****************************/
