/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: battery0_23x14                                        *
* Dimensions:  23 * 14                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include "bmp_battery.h"
#include <stdlib.h>

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsbattery0_23x14[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palbattery0_23x14 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsbattery0_23x14[0]
};

static GUI_CONST_STORAGE unsigned char _acbattery0_23x14[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXX_____, ________, __XXXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_XXXX, XXXXXXXX, X__XXXX_,
  XXX_XXXX, XXXXXXXX, X___XXX_,
  XXX_XXXX, XXXXXXXX, X___XXX_,
  XXX_XXXX, XXXXXXXX, X___XXX_,
  XXX_XXXX, XXXXXXXX, X__XXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_____, ________, __XXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmbattery0_23x14 = {
  23, // xSize
  14, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acbattery0_23x14,  // Pointer to picture data (indices)
  &_Palbattery0_23x14   // Pointer to palette
};


/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsbattery34_23x14[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palbattery34_23x14 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsbattery34_23x14[0]
};

static GUI_CONST_STORAGE unsigned char _acbattery34_23x14[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXX_____, ________, __XXXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_X___, XXXXXXXX, X__XXXX_,
  XXX_X___, XXXXXXXX, X___XXX_,
  XXX_X___, XXXXXXXX, X___XXX_,
  XXX_X___, XXXXXXXX, X___XXX_,
  XXX_X___, XXXXXXXX, X__XXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_____, ________, __XXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmbattery34_23x14 = {
  23, // xSize
  14, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acbattery34_23x14,  // Pointer to picture data (indices)
  &_Palbattery34_23x14   // Pointer to palette
};

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsbattery67_23x14[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palbattery67_23x14 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsbattery67_23x14[0]
};

static GUI_CONST_STORAGE unsigned char _acbattery67_23x14[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXX_____, ________, __XXXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_X___, X___XXXX, X__XXXX_,
  XXX_X___, X___XXXX, X___XXX_,
  XXX_X___, X___XXXX, X___XXX_,
  XXX_X___, X___XXXX, X___XXX_,
  XXX_X___, X___XXXX, X__XXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_____, ________, __XXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmbattery67_23x14 = {
  23, // xSize
  14, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acbattery67_23x14,  // Pointer to picture data (indices)
  &_Palbattery67_23x14   // Pointer to palette
};

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsbattery100_23x14[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palbattery100_23x14 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsbattery100_23x14[0]
};

static GUI_CONST_STORAGE unsigned char _acbattery100_23x14[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXX_____, ________, __XXXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_X___, X___X___, X__XXXX_,
  XXX_X___, X___X___, X___XXX_,
  XXX_X___, X___X___, X___XXX_,
  XXX_X___, X___X___, X___XXX_,
  XXX_X___, X___X___, X__XXXX_,
  XXX_XXXX, XXXXXXXX, X_XXXXX_,
  XXX_____, ________, __XXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_,
  XXXXXXXX, XXXXXXXX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmbattery100_23x14 = {
  23, // xSize
  14, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acbattery100_23x14,  // Pointer to picture data (indices)
  &_Palbattery100_23x14   // Pointer to palette
};
/*************************** End of file ****************************/
