/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: dividing_128x1                                        *
* Dimensions:  128 * 1                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include "bmp_dividing.h"
#include <stdlib.h>

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsdividing_128x1[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Paldividing_128x1 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsdividing_128x1[0]
};

static GUI_CONST_STORAGE unsigned char _acdividing_128x1[] = {
  ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmdividing_128x1 = {
  128, // xSize
  1, // ySize
  16, // BytesPerLine
  1, // BitsPerPixel
  _acdividing_128x1,  // Pointer to picture data (indices)
  &_Paldividing_128x1   // Pointer to palette
};

/*************************** End of file ****************************/
