/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mini_mabot_43x14                                      *
* Dimensions:  43 * 14                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include "bmp_mini_mabot.h"
#include <stdlib.h>

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsmini_mabot_43x14[] = {
  0x000000, 0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palmini_mabot_43x14 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsmini_mabot_43x14[0]
};

static GUI_CONST_STORAGE unsigned char _acmini_mabot_43x14[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XX__XXXX, XXX__XXX, XXXXX__X, XXXXXXXX, XXXXX__X, XXX_____,
  XX___XXX, XX___XXX, XXXXX__X, XXXXXXXX, XXXXX__X, XXX_____,
  XX___XXX, XX___XXX, XXXXX__X, XXXXXXXX, XXXXX__X, XXX_____,
  XX___XXX, XX___XX_, ___XX___, ___XXXX_, ___XX___, _XX_____,
  XX____XX, X____X__, ____X___, ____XX__, ____X___, _XX_____,
  XX____XX, X_______, XX______, XX______, XX_____X, XXX_____,
  XX_____X, _______X, XXX____X, XXX____X, XXX____X, XXX_____,
  XX__X__X, __X____X, XXX____X, XXX____X, XXX____X, XXX_____,
  XX__X___, __X_____, XX______, XX__XX__, XX__X__X, XXX_____,
  XX__XX__, _XX__X__, _____X__, ____XX__, ____X___, _XX_____,
  XX__XX__, _XX__XX_, __X__XX_, ___XXXX_, ___XXX__, _XX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____
};

GUI_CONST_STORAGE GUI_BITMAP bmmini_mabot_43x14 = {
  43, // xSize
  14, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acmini_mabot_43x14,  // Pointer to picture data (indices)
  &_Palmini_mabot_43x14   // Pointer to palette
};

/*************************** End of file ****************************/
